services:

  # Adobe ColdFusion server.
  # http://localhost:8080/
  #
  # Administrator / CFIDE:
  # - Url: http://localhost:8080/CFIDE/administrator/index.cfm
  # - Password: commandbox
  acf2025:
    image: "cfmailml-acf2025:dev"
    pull_policy: "never"
    build:
      context: "."
      dockerfile: "docker/acf2025/Dockerfile"
    ports:
      - "8080:8080"
    volumes:
      - "./:/app"
      - "../cfmailml/:/cfmailml"
    networks:
      - app_network
    healthcheck:
      test: "echo hello"

  # Lucee CFML server.
  # http://localhost:8081/
  #
  # Administrator:
  # - Url: http://localhost:8081/lucee/admin/server.cfm
  # - Password: commandbox
  lucee6:
    image: "cfmailml-lucee6:dev"
    pull_policy: "never"
    build:
      context: "."
      dockerfile: "docker/lucee6/Dockerfile"
    ports:
      - "8081:8080"
    volumes:
      - "./:/app"
      - "../cfmailml/:/cfmailml"
    networks:
      - app_network
    healthcheck:
      test: "echo hello"

networks:
  app_network:
    name: cfmailml_network
